### ISSUE TITLE
NUnit tests crash when updating to Xamarin.Forms 3.6 and Xamarin.Forms.Mocks 3.5

### ISSUE THREAD

**Issue by henrik-stromberg-tetrapak** [jonathanpeppers/Xamarin.Forms.Mocks#38]

**Comment by henrik-stromberg-tetrapak** [comment]
I have a very simple viewCell with a trigger. like this.
<?xml version="1.0" encoding="UTF-8"?>
<ViewCell xmlns="http://xamarin.com/schemas/2014/forms" 
          xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
          x:Class="UnitTestFailsApp.DataTemplates.SparePartViewCell"
          x:Name="this"
          IsEnabled="{Binding IsEnabled}"
          StyleId="none">
    
    <ViewCell.View>
        
        <Grid Padding="10,0,0,10" IsEnabled="{Binding IsEnabled}"  RowSpacing="0" AutomationId="SparePartViewCell">
             <Grid.Triggers>
                    <Trigger TargetType="Grid"
                        Property="IsEnabled" Value="False">
                          <Setter Property="Opacity" Value="0.6" />
                          <Setter Property="BackgroundColor" Value="{x:StaticResource DisabledbackgroundColor}"/>
                      </Trigger>
                </Grid.Triggers>
        </Grid>
        
        
    </ViewCell.View>
</ViewCell>

the unit test looks like this

public class UnitTest1
    {
        [SetUp]
        public void SetUp()
        {
            Xamarin.Forms.Mocks.MockForms.Init();
        }

        [Test]
        public void Can_convert_without_highlight_match_on_code()
        {          
            var sparePartView = new SparePartViewCell(); ;
        }
    }

I get the following exception in my test 
at Xamarin.Forms.Mocks.Xaml.ValueConverterProvider.Convert(Object value, Type toType, Func`1 minfoRetriever, IServiceProvider serviceProvider)
   at Xamarin.Forms.PropertyCondition.set_Property(BindableProperty value) in D:\a\1\s\Xamarin.Forms.Core\Interactivity\PropertyCondition.cs:line 44
   at Xamarin.Forms.Trigger.set_Property(BindableProperty value) in D:\a\1\s\Xamarin.Forms.Core\Interactivity\Trigger.cs:line 27
   at UnitTestFailsApp.DataTemplates.SparePartViewCell.InitializeComponent() in /Users/sestrombergh/Projects/UnitTestFailsApp/UnitTestFailsApp/obj/Debug/netstandard2.0/DataTemplates/SparePartViewCell.xaml.g.cs:line 26
   at UnitTestFailsApp.DataTemplates.SparePartViewCell..ctor() in /Users/sestrombergh/Projects/UnitTestFailsApp/UnitTestFailsApp/DataTemplates/SparePartViewCell.xaml.cs:line 12
   at TestForApp.UnitTest1.Can_convert_without_highlight_match_on_code() in /Users/sestrombergh/Projects/UnitTestFailsApp/TestForApp/UnitTest1.cs:line 19

**Comment by jonathanpeppers** [comment]
@henrik-stromberg-tetrapak are you sure this is breaking in 3.5.x? What is the full version number of 3.5.x you saw this on?

I can see it with 3.6.0.220655, for sure.

**Comment by jonathanpeppers** [comment]
@henrik-stromberg-tetrapak can you try: https://www.nuget.org/packages/Xamarin.Forms.Mocks/3.5.0.1

I just pushed it, but should be available shortly.
