### ISSUE TITLE
ArgumentNullException: Value cannot be mull. (Parameter 'targetObject')

### ISSUE THREAD

**Issue by AlexeyStarkov** [jonathanpeppers/Xamarin.Forms.Mocks#73]
Hello. I try to create unit tests for my custom control which uses style from Application.Current.Resources.MergedDictionaries. Everything works fine when I launch my application, but when I try to test the control using Xamarin.Forms.Mocks I get an exception during InitializeComponent() call of the control under test.
**Message**: Value cannot be null. (Parameter 'targetObject')
**Stack trace**:
 at Xamarin.Forms.Setter.Apply(BindableObject target, Boolean fromStyle)
   at Xamarin.Forms.Style.ApplyCore(BindableObject bindable, Style basedOn)
   at Xamarin.Forms.Style.Xamarin.Forms.IStyle.Apply(BindableObject bindable)
   at Xamarin.Forms.MergedStyle.set_Style(IStyle value)
   at Xamarin.Forms.NavigableElement.<>c.<.cctor>b__22_0(BindableObject bindable, Object oldvalue, Object newvalue)
   at Xamarin.Forms.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Xamarin.Forms.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes)
   at Xamarin.Forms.Element.OnResourceChanged(BindableProperty property, Object value)
   at Xamarin.Forms.Element.OnSetDynamicResource(BindableProperty property, String key)
   at Xamarin.Forms.BindableObject.SetDynamicResource(BindableProperty property, String key, Boolean fromStyle)
   at Xamarin.Forms.BindableObject.Xamarin.Forms.Internals.IDynamicResourceHandler.SetDynamicResource(BindableProperty property, String key)
   at [ProjectName].[ControlName].InitializeComponent() in .../src/Lib/UI/[ProjectName]/obj/Debug/netstandard2.1/Controls/[ControlName].xaml.g.cs:line 34
   
   My question:
   Is Xamarin.Forms.Mocks supposed to work for controls or views that use Styles?

**Comment by jonathanpeppers** [comment]
Can you make a quick example of a test that fails? We can fix this and add your test to the suite.

**Comment by AlexeyStarkov** [comment]
Sorry for that. I've found a bug in one of styles of my application.
